# Generated by Django 5.2.1 on 2025-06-26 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoHistorico',
            fields=[
                ('consumoHistoricoId', models.AutoField(primary_key=True, serialize=False)),
                ('consumoTotal', models.FloatField()),
                ('maxConsumo', models.FloatField()),
                ('minConsumo', models.FloatField()),
                ('fechaPeriodo', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
