# Generated by Django 5.2.1 on 2025-06-26 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoMensaje', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacionId', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fechaEnvio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipoMensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoMensaje.tipomensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
