# Generated by Django 5.2.1 on 2025-06-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreSensor', models.CharField(max_length=100)),
                ('fechaInscripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
