# Generated by Django 5.2 on 2025-07-14 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='usuario',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario'),
            preserve_default=False,
        ),
    ]
