# Generated by Django 5.2.1 on 2025-06-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMensaje',
            fields=[
                ('tipoMensajeId', models.AutoField(primary_key=True, serialize=False)),
                ('tipoAlerta', models.CharField(max_length=100)),
                ('mensaje_default', models.TextField()),
            ],
        ),
    ]
