# Generated by Django 5.2.1 on 2025-06-26 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoEnvio',
            fields=[
                ('tiempoEnvioId', models.AutoField(primary_key=True, serialize=False)),
                ('tiempoSegundos', models.IntegerField()),
                ('fechaCambio', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
